routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('users', 'UserController')->names('home.users');

Route::group(['middleware' => 'role:admin'], function() {
    Route::get('/admin', function() {
        return 'Добро пожаловать, ' . auth()->user()->name . '.';
    });
});

app/Models/Permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    public function roles()
    {
        return $this->belongsToMany(Role::class,'roles_permissions');
    }

}

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function permissions()
    {
        return $this->belongsToMany(Permission::class,'roles_permissions');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\HasRolesAndPermissions;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, HasRolesAndPermissions;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'surname', 'name', 'phone', 'email', 'password', 'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image as ImageInt;


class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function upload(Request $request)
    {
        $file = $request->file('file');
        // отображаем имя файла
        $name = $file->getClientOriginalName();
        //отображаем расширение файла
        $file->getClientOriginalExtension();
        //отображаем фактический путь к файлу
        $file->getRealPath();
        //отображаем размер файла
        $file->getSize();
        //отображаем Mime-тип файла
        $file->getMimeType();
        //перемещаем загруженный файл
        $destinationPath = 'profile_avatar';
        $file->move($destinationPath,$file->getClientOriginalName());

        $id = auth()->user()->id;
        $user_profile = User::find($id);
        $user_profile->avatar = $name;
        $user_profile->save();

        return redirect()->route('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{

    public function index()
    {
        $id = auth()->user()->id;
        $user = User::find($id);
        return view('user.home',['user' => $user]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $user = User::find($id);

        return view('user.edit',['user' => $user]);
    }

    /**
     * @param Request $request
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, User $user)
    {
        $file = $request->file('file');
        $image_name = date('Y-m-d') . '.' . $file->getClientOriginalExtension();
        // перемещаем в указаную папку
        $destinationPath = public_path('profile_avatar\\');
        $destinationPathSmall = public_path('img_small_profile\\');
        $resize_image = Image::make($file->getRealPath());
        $resize_image->resize(250, 250, function($constraint){
            $constraint->aspectRatio();
        })->save($destinationPathSmall  . '/' . $image_name);

        if ($file) {
            $file->move($destinationPath, $file->getClientOriginalName());
        }

        $user->surname = $request['surname'];
        $user->name = $request['name'];
        $user->phone = $request['phone'];
        $user->email = $request['email'];
        if (empty($user->avatar)) {
            $user->avatar = $file->getClientOriginalName();
        }
        $request['password'] == null ?: $user->password = bcrypt($request['password']);
        $user->save();

        if (!$user) {
            return back()
                ->withErrors(['msg' => 'Ошибка сохранения'])
                ->withInput();
        } else {
            return redirect()
                ->route('home.users.index')
                ->with(['success' => 'Успешно сохранено']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/home_page_style.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</body>
</html>

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Main content -->
<section class="container-fluid">
    <div class="row">
        <div class="offset-3 col-md-6">
            <div class="box">
                <form action="{{ route('home.users.update', $user->id) }}" enctype="multipart/form-data" method="POST"
                      data-toggle="validator">
                    @method('PUT')
                    @csrf
                    <div class="box-body">

                        <div class="form-group has-feedback">
                            <label for="surname">Фамилия</label>
                            <input type="text" class="form-control" name="surname" id="surname"
                                   value="@if(old('surname')){{old('surname')}}@else{{$user->surname ?? ''}} @endif" required>
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-feedback">
                            <label for="name">Имя</label>
                            <input type="text" class="form-control" name="name" id="name"
                                   value="@if(old('name')){{old('name')}}@else{{$user->name ?? ''}} @endif" required>
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-feedback">
                            <label for="phone">Телефон</label>
                            <input type="text" class="form-control" name="phone" id="phone"
                                   value="@if(old('phone')){{old('phone')}}@else{{$user->phone ?? ''}} @endif" required>
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-feedback">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" name="email" id="email"
                                   value="@if(old('email')){{old('email')}}@else{{$user->email ?? ''}} @endif" required>
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <div class="form-group">
                            <label for="">Пароль</label>
                            <input type="text" class="form-control" name="password"
                                   placeholder="Введите пароль,если хотите его изменить">
                        </div>
                        <div class="form-group">
                            <label for="">Подтверждение пароля</label>
                            <input type="text" class="form-control" name="password_confirmation"
                                   placeholder="Подтверждение пароля">
                        </div>
                        <br>
                        <div class="form-group">
                            <div class="custom-file">
                                <input type="file" name="file" class="custom-file-input">
                                <label class="custom-file-label" for="inputGroupFile03">Загрузить фото профиля</label>
                            </div>
                        </div>

                        <div class="box-footer">
                            <input type="hidden" name="id" value="{{ $user->id }}">
                            <button type="submit" class="btn btn-success">Сохранить</button>
                        </div>
                    </div>
                </form>
        </div>
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/user/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container emp-profile">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    @if (!empty($user->avatar))
                        <img src="{{ asset('profile_avatar/' . $user->avatar ) }}" alt="Profile"/>
                    @else
                        <img src="{{ asset('img/user_avatar.png') }}" alt="Avatar">
                    @endif
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h6>{{$user->name}}</h6>
                    <h5>{{$user->surname}}</h5>
                    <br>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" role="tab"
                               aria-controls="home" aria-selected="true">Профиль</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <a href="{{ route('home.users.edit', $user->id) }}"
                   title="Редактировать профиль">
                    <i class="btn btn-xs"></i>
                    <button type="submit" class="btn btn-success
                                                btn-xs">Редактировать</button>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>WORK LINK</p>
                    <a href="">Website Link</a><br/>
                    <p>SKILLS</p>
                    <a href="">Web Designer</a><br/>
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Фамилия</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{$user->surname}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Имя</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{$user->name}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>E-mail</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{$user->email}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Номер телефона</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{$user->phone}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection